---
title: " Check raw data and experimental conditions"
author: "Jiayu Li"
date: "12 July 2023"
output:
  html_document:
    toc: true
    theme: united
---

```{r, include=FALSE}
source("R/read_clean_data_without_condi.R")
library(plotly)
library(DT)
```


# Conditions
```{r echo=FALSE}
library(DT)
cond_general_scenario <- fread("clean_data/conditions/general_scenario.csv")
cond_innova_vc <- fread("clean_data/conditions/innova_vc.csv")
cond_source_and_receptor <- fread("clean_data/conditions/source_and_receptor.csv")
cond_wind_sensor <- fread("clean_data/conditions/wind_sensor.csv")

# cond_general_scenario[, start_datetime := dmy_hm(paste(exp_date, start_time) ) - hours(8)]
# cond_general_scenario[, end_datetime := dmy_hm(paste(exp_date, end_time) )- hours(8)]

  # datatable(cond_general_scenario)
  

```

## General conditions
```{r echo=FALSE}
cond_general_scenario[, note := iconv(note, to = "utf-8")]
cond_general_scenario  %>%
  datatable( rownames = FALSE, filter = "top" )# %>% formatDate(c("start_datetime","end_datetime"), method = "toLocaleString")
```

## Innova conditions
```{r echo=FALSE}
    cond_innova_vc %>% datatable(rownames = FALSE, filter = "top")
```

## Source and receptor conditions
```{r echo=FALSE}
    cond_source_and_receptor %>% datatable(rownames = FALSE, filter = "top" )
```

## Wind sensor conditions
```{r  echo=FALSE}
    cond_wind_sensor %>% datatable(rownames = FALSE, filter = "top" )
```





# Raw data

## Innova:

```{r echo=FALSE}
library(DT)
# https://medium.com/@SportSciData/https-medium-com-collinsneil306-how-to-create-interactive-reports-with-r-markdown-part-i-4fa9df46cd9
# https://rstudio.github.io/DT/functions.html
# https://youtu.be/qLEkUjxk7e8  Yihui Xie | One R Markdown Document, Fourteen Demos | RStudio (2020)
copy(dt_innova)[, c("datetime","sf6_conc","innova_ch")][, datetime := datetime - hours(8)] %>% 
  .[, innova_ch := paste0("innova_ch_", innova_ch,"_sf6_ppm")] %>%
  .[, c("datetime","sf6_conc","innova_ch")] %>% dcast(datetime ~ innova_ch, value.var = "sf6_conc") %>%
  datatable( rownames = FALSE, filter = "top" ) %>% formatRound(c(2:7), 3) %>% formatDate('datetime', method = "toLocaleString")
```

Raw data measured by Innova are plotted using the codes below:

```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- dt_innova[, time_ := hms::as_hms(paste( hour(datetime), minute(datetime), second(datetime), sep = ":") )]%>% 
  .[, innova_ch := paste("Ch.", innova_ch)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, sf6_conc, color = innova_ch) ) +
  geom_line() + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("Innova channels")+
  # guides(color = guide_legend(nrow = 1)) +
  scale_y_log10("SF6 concentration (ppm)") +
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) #+
  # theme(legend.position = "top")

ggplotly(p)
```


## VelociCalc
### Velocity
```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
copy(dt_velocicalc)[, time_ := hms::as_hms(paste( hour(datetime), minute(datetime), second(datetime), sep = ":") )]%>% 
  .[, vc_unit := paste("VC-", vc_unit)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, vel, color = paste("VC-", vc_unit))) +
  geom_line() + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("VC unit")+
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```

### Temperature
```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
copy(dt_velocicalc)[, time_ := hms::as_hms(paste( hour(datetime), minute(datetime), second(datetime), sep = ":") )]%>% 
  .[, vc_unit := paste("VC-", vc_unit)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, temperature, color = vc_unit)) +
  geom_line() + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("VC unit")+
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```

### Relative Humidity
```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
copy(dt_velocicalc)[, time_ := hms::as_hms(paste( hour(datetime), minute(datetime), second(datetime), sep = ":") )]%>% 
  .[, vc_unit := paste("VC-", vc_unit)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, RH, color = vc_unit)) +
  geom_line() + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("VC unit")+
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```

## Wind sensor
### Data from $WIMDA <19>

```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
  copy(dt_wind_sensor)[, time_ := hms::as_hms(format(datetime, format = "%H:%M:%S") )] %>% 
  .[, wind_sensor_unit := paste("Station", wind_sensor_unit)] %>%
  .[!is.na(time_)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, vel_mag_WIMDA_19 , color = wind_sensor_unit)) +
  geom_line() + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("Wind sensor unit") +
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```

## Data from $WIMWV <3>
```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
  copy(dt_wind_sensor)[, time_ := hms::as_hms(format(datetime, format = "%H:%M:%S") )] %>% 
  .[, wind_sensor_unit := paste("Station", wind_sensor_unit)] %>%
  .[!is.na(time_)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, vel_mag_WIMWV_3 , color = wind_sensor_unit)) +
  geom_line() + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("Wind sensor unit") +
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```

### Data from $WIMDA <13>
```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
  copy(dt_wind_sensor)[, time_ := hms::as_hms(format(datetime, format = "%H:%M:%S") )] %>% 
  .[, wind_sensor_unit := paste("Station", wind_sensor_unit)] %>%
  .[!is.na(time_)] %>%
  setorder(datetime) %>%
  ggplot(aes(time_, vel_angle_WIMDA_13 , color = wind_sensor_unit)) +
  geom_point(size = 0.5) + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("Wind sensor unit") +
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```

### Data from $WIMWV <1>
```{r fig.height=35, fig.width=8, message=FALSE, warning=FALSE}
p <- 
  copy(dt_wind_sensor)[, time_ := hms::as_hms(format(datetime, format = "%H:%M:%S") )] %>% 
  .[, wind_sensor_unit := paste("Station", wind_sensor_unit)] %>%
  .[!is.na(time_)] %>%
  setorder(datetime) %>%
  # .[, test_id := fct_inorder(paste("Test",test_id)) ] %>% 
  ggplot(aes(time_, vel_angle_WIMWV_1 , color = wind_sensor_unit)) +
  geom_point(size = 0.5) + 
  facet_grid(fct_inorder(format(date(datetime), format = "%b %d"))~., scales = "free_y") +
  scale_color_discrete("Wind sensor unit") +
  coord_cartesian(xlim = c(hms::as_hms("10:00:00"),hms::as_hms("22:00:00")) ) +
  theme(legend.position = "top")

ggplotly(p)
```
